version: "3.8"

services:
  db:
    image: postgres:15
    container_name: interview_db
    environment:
      POSTGRES_DB: interview_app
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./BackEnd/interview_app
    container_name: interview_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/interview_app
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_MAIL_USERNAME: sampledemk@gmail.com
      SPRING_MAIL_PASSWORD: fifmhrpftrkesskx
    depends_on:
      - db

  frontend:
    build: ./FrondEnd/togglemax_app
    container_name: interview_frontend
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend

volumes:
  pgdata:
