services:
  db:
    image: postgres:15
    container_name: interview_db
    environment:
      POSTGRES_DB: interview_app
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./BackEnd/interview_app
    container_name: interview_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://interview_db:5432/interview_app
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_MAIL_USERNAME: sampledemk@gmail.com
      SPRING_MAIL_PASSWORD: fifmhrpftrkesskx
    depends_on:
      - db
    networks:
      - app-network


  frontend:
    build:
      context: ./FrondEnd/togglemax_app
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: interview_frontend
    env_file:
      - ./FrondEnd/togglemax_app/.env
    environment:
      INTERNAL_API_URL: ${INTERNAL_API_URL}
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - app-network


volumes:
  pgdata:

networks:
  app-network:
