import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Logo from "../(dashboard)/layout_components/logo";  

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="h-screen w-full bg-black flex flex-col pt-10 pb-10">
      <nav className="flex flex-col items-center justify-center p-4 mt-0" style={{ backgroundColor: "#ffffff" }}>
        <Logo />
      </nav>

        {children}

    </div>
  );
}
