"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Nav from "./layout_components/nav"
import Sidebar from "./layout_components/sidebar";
import useAuth from "@/hooks/useAuth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useAuth();

  return (
    <div className="flex absolute top-0 left-0 right-0">
        
        <div>
            <Sidebar />
        </div>

        <div className="h-screen w-full none overflow-y-auto">
            <Nav />
            <main className="dark:bg-black-100 p-4">  {children} </main>
        </div>

    </div>
  );
}
