# --- Build Stage ---
FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

# Copy the project files
COPY . .

# Grant mvnw permission
RUN chmod +x mvnw

# Build the JAR file (skip tests for faster build)
RUN ./mvnw clean package -DskipTests


# --- Runtime Stage ---
FROM eclipse-temurin:21-jre

WORKDIR /app

# Copy only the built JAR file from builder
COPY --from=builder /app/target/interview_app-0.0.1-SNAPSHOT.jar app.jar

# Expose the port
EXPOSE 8080

# Run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
