# --- Build stage ---
FROM node:22-alpine AS builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the source code
COPY . .

# Inject build-time environment variable
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

# Build the Next.js app
RUN npm run build


# --- Production stage ---
FROM node:22-alpine AS runner

WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.mjs ./next.config.mjs
COPY --from=builder /app/postcss.config.mjs ./postcss.config.mjs

# Runtime environment variable for Next.js server usage
ENV INTERNAL_API_URL=$INTERNAL_API_URL

# Set environment variable
ENV NODE_ENV production

EXPOSE 3000

# Start the app
CMD ["npm", "start"]






# FROM node:22-jdk

# WORKDIR /app

# # Only copy package files to install dependencies
# COPY package*.json ./

# # Install deps globally and locally
# RUN npm install

# EXPOSE 3000

# CMD ["npm", "run", "dev"]
