FROM node:22-alpine

WORKDIR /app

# Only copy package files to install dependencies
COPY package*.json ./

# Install deps globally and locally
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]


# FROM node:20-alpine AS builder
# WORKDIR /app
# COPY . .
# RUN npm install
# RUN npm run build

# FROM node:20-alpine
# WORKDIR /app
# COPY --from=builder /app ./
# EXPOSE 3000
# CMD ["npm", "start"]
